### PR TITLE
Add php8 support

### PR DESCRIPTION
**Pull request by HanakJakub**
This branch is adding PHP 8 support

### CODE REVIEW

**Comment by HanakJakub** [comment]
@cs278 Hey, just checking, are you planning to add support for PHP8 or not?

**Comment by cs278** [comment]
Fab thanks, I'll look at merging this this weekend.

**Comment by MacroMan** [comment]
Sorry to pester, but is there any chance of merging this soon? I've got a project held up until I can use this package.

**Review by cs278 — APPROVED** [review]

**Comment by cs278** [comment]
Thanks @HanakJakub

**Comment by cs278** [comment]
@HanakJakub @MacroMan released https://github.com/cs278/bank-modulus/releases/tag/v1.12.0

**Pull request merged**
